### PR TITLE
Tindog, Tinder for dogs

### PR DESCRIPTION
**Pull request by smil-thakur**
added a full designed website like tinder , but with a twist can be helpful for getting button design and images and cool alignment tricks

### CODE REVIEW

**Comment by smil-thakur** [comment]
@yagamipal added tindog project please review thanks in adv

**Comment by smil-thakur** [comment]
@yagamipal added tindog project please review thanks in adv

**Comment by smil-thakur** [comment]
@yagamipal added tindog project please review thanks in adv

**Comment by roshankcpkr** [comment]
accepted project

**Pull request merged**
